name: Hello World
description: Says hello to the world
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: composite
  steps:
    - name: Greet
      run: echo "Hello ${{ inputs.who-to-greet }}!"
      shell: bash